window.CLOSURE_NO_DEPS = true;(function() {var e=!0,i=!1;function j(a,b,d){this.key=a;this.value=b;this.c=d}j.prototype.getKey=function(){return this.key};function s(a){return a?(a^16*Math.random()>>a/4).toString(16):([1E7]+-1E3+-4E3+-8E3+-1E11).replace(/[018]/g,s)}function t(){for(var a=document.cookie.split(";"),b=0;b<a.length;b++){var d=a[b].substr(0,a[b].indexOf("=")),c=a[b].substr(a[b].indexOf("=")+1),d=d.replace(/^\s+|\s+$/g,"");if("__jwpusr"==d)return unescape(c)}}function u(a){var b=[];b.push("__jwpusr="+escape(a));a=new Date;a.setDate(a.getDate()+365);b.push("expires="+a.toUTCString());b.push("path=/");document.cookie=b.join(";")}
function v(a,b){if(a==document)return e;if(!a||!a.parentNode||0===a.offsetWidth||0===a.offsetHeight)return i;var d=[];a.style&&d.push(a.style);window.getComputedStyle&&d.push(window.getComputedStyle(a,""));a.currentStyle&&d.push(a.currentStyle);for(var c=0;c<d.length;c++)for(var f=0;f<b.length;f++){var g=b[f].key;if(("opacity"==g?parseFloat(d[c][g]):d[c][g])===b[f].value)return i}return v(a.parentNode,b)}
function w(a,b){var d=document.getElementById(a),c=[{key:"visibility",value:"hidden"},{key:"display",value:"none"}];b||c.push({key:"opacity",value:0});var f;a:{f=d.getBoundingClientRect();if(f=document.elementFromPoint((f.left+f.right)/2,(f.top+f.bottom)/2))for(;f!=document;){if(f==d){f=e;break a}f=f.parentNode}f=i}return f&&v(d,c)};function x(){if(window._jwplayertracker)return window._jwplayertracker;window._jwplayertracker=this;this.b={};this.l="jwpltx.com";this.f=this.d="n";this.k="v1/jwplayer6/ping.gif?";this.j=window.jwplayer.version;this.i=window.location.href;this.h=document.title;this.g=document.referrer;this.e=window.top.location.href==window.location.href?0:1;this.m=2808}
function y(a,b,d,c,f,g){a.b[c]||(a.b[c]={});a.b[c][f]||(a.b[c][f]={});b=z(a,b,d,c,f,g);a.b[c][f][b]&&(b+="&dup=1");(new Image).src=b;a.b[c][f][b]=e}
function z(a,b,d,c,f,g){d=[new j("tv",a.m,0),new j("dt",Math.round((new Date).getTime()/1E3),1),new j("n",("0000000000000000"+Math.random().toString().substring(2)).slice(-16),2),new j("uc",d,3),new j("aid",c,4),new j("e",f,5),new j("i",a.e,6),new j("pv",a.j,7),new j("pu",a.i,8),new j("pt",a.h,100),new j("r",a.g,200)];0<g.length&&(d=d.concat(g));d.sort(function(a,b){return a.c>b.c?1:-1});g=[];for(c=0;c<d.length;c++)g.push(d[c].getKey()+"="+encodeURIComponent(d[c].value));return["https:"==document.location.protocol?
"https://s.":"http://i.",b?a.d:a.f,".",a.l,"/",a.k,g.join("&")].join("")}function A(a){for(var b in a.b)if(a.b[b].pv)return e;return i};function B(a){this.a=a}function C(a,b){a.a.onReady(b)}function D(a,b){a.a.onIdle(b)}function E(a,b){a.a.onPlaylistItem(b)}function F(a,b){a.a.onPlay(b)}function G(a){return a.a.getRenderingMode()}function H(a){return a.a.config.autostart?a.a.config.autostart:i};function I(a,b){if(b.enabled!==i){var d;if(window.jwplayer.key){var c=new window.jwplayer.utils.key(window.jwplayer.key);"invalid"!=c.edition()&&(d=c.token())}d||(d="_");var f=i,g=new B(a),p=e;"undefined"!=typeof b.cookies&&(p=b.cookies?e:i);var l;navigator.cookieEnabled===i?l="-":p===i?l="_":(c=t(),"undefined"==typeof c?(c=s(),u(c),l=c==t()?c:"0"):l=c);var r=new x;A(r)||y(r,p,l,d,"pv",[]);C(g,function(){var a="html5"==G(g).toLowerCase();y(r,p,l,d,"e",[new j("m","html5"==G(g).toLowerCase()?1:0,10),
new j("a","true"==H(g).toString().toLowerCase()?1:0,11),new j("v",w(g.a.id,a)?1:0,12),new j("w",g.a.getWidth(),13),new j("h",g.a.getHeight(),14)])});D(g,function(){f=e});E(g,function(){f=e});F(g,function(){if(f){f=i;var a=g.a.getPlaylist(),b=g.a.getPlaylistItem(),c=b.file;if(b.sources){for(var n=[],k=b.sources.length-1;0<=k;k--)b.sources[k].url?n.push(b.sources[k].url):b.sources[k].file&&n.push(b.sources[k].file);n.sort();c=n[0]}var n=p,k=l,J=d,K=new j("m","html5"==G(g).toLowerCase()?1:0,10),L=new j("a",
"true"==H(g).toString().toLowerCase()?1:0,11),M=new j("v",w(g.a.id,i)?1:0,12),N=new j("w",g.a.getWidth(),13),O=new j("h",g.a.getHeight(),14),P=new j("f",g.a.getFullscreen()?1:0,15),a=new j("pl",a.length,16),Q=new j("l",b.duration,17),h;var m=c.indexOf("://"),q=c.indexOf("?");if(0<m&&(0>q||q>m))h=c;else{h||(h=document.location.href);m=h.substring(0,h.indexOf("://")+3);q=h.substring(m.length,h.indexOf("/",m.length+1));0===c.indexOf("/")?h=c.split("/"):(h=h.split("?")[0],h=h.substring(m.length+q.length+
1,h.lastIndexOf("/")),h=h.split("/").concat(c.split("/")));for(var c=[],o=0;o<h.length;o++)h[o]&&"."!=h[o]&&(".."==h[o]?c.pop():c.push(h[o]));h=m+q+"/"+c.join("/")}y(r,n,k,J,"s",[K,L,M,N,O,P,a,Q,new j("mu",h,18),new j("t",b.title,19),new j("id",b.mediaid,101),new j("k",b.tags,102),new j("lu",b.link,103),new j("d",b.description,201)])}})}}window.jwplayer&&window.jwplayer()&&window.jwplayer().registerPlugin("jwpsrv","6.0",I);})();
